dist: trusty

language: go

go:
  - 1.13.1

env:
  global:
    - TIO_VERSION=v0.1.0
    - TIO_CONSUL_AGENT=tioserverless/consul-agent
    - TIO_CONSUL_WATCH=tioserverless/consul-watch

addons:
  sonarcloud:
    organization: "tio-serverless"
    token:
      secure: "fLX9+eb0B0tU6Bws6LMvrT4C2fHIGZzvuNAvVxN2w3gxRA8zvr5ldR7rQzC6iJBEzUxNgzmSxRe0FVvgVXMqZWfyKLBKGSxA040Qlvqe8+yqc1vjgLKHFJuFVZ9nygX/NE7U8EIU1b3kEcCbYC4FFMxE26fmxg6N7nXqiRmraToKBYOiJj/9RNOmjFZMlyNIYBzGSvV6zbVaWxoQzo9GsJCnzmXB8t9AtTIFoOfefZY3mcZGMPnMFVpGS12sCWY6SChXYBhdpy8m00J56sm8fdj09S8RimgRDOGawByzdxH+GvuvwE6U95Rc5TIu1Pe1bwuV4SyvSQJ91d/RsRFgUpIfkliY8II0/ZUn4kMaAvaNleeZXz66IV1BZC4tys+K4TkjBFsDfu9Z1oOVl3Dqo/IZpvFhc+WHJax3fJoXWiOUXTao4tPV0vPoJTkXDw/5KHijqRINLfP2XVCE4j8w8EkDglArqHI5dd3c9HWaX1u5gPxnWwtfnbToIiL8Sv/GAemQspU92AN5fA9I/5+KVFpA1+yowhDeGCgqGjoDTdCdgOkh6/CqekMafRykDJUnoCjmlbC/7988OTbc3oca+iKFet1rw80rvyZdOYvO2cBAfr3R/8qCYW6cxlA5Lc3eBWzUYWGK/mTnAOf0mR/NDbj+sCOFlgdjpxRJvxhcO4A="

script:
  - sonar-scanner

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USER" --password-stdin
  - go get github.com/golang/mock/gomock
  - go get github.com/golang/mock/mockgen

install:
  - go test ./...
  - go build -mod=vendor -ldflags "-X main._VERSION_=$TIO_VERSION -X main._BRANCH_=$TRAVIS_BRANCH" -o bin/consul-agent sidecar/*.go
  - go build -mod=vendor -ldflags "-X main._VERSION_=$TIO_VERSION -X main._BRANCH_=$TRAVIS_BRANCH" -o bin/tio-consul-watch watch/*.go

after_script:
  - docker build -t ${TIO_CONSUL_AGENT}:${TIO_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.consul-sidecar .
  - docker push ${TIO_CONSUL_AGENT}:${TIO_VERSION}-${TRAVIS_BRANCH}
  - docker build -t ${TIO_CONSUL_WATCH}:${TIO_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.consul-watch .
  - docker push ${TIO_CONSUL_WATCH}:${TIO_VERSION}-${TRAVIS_BRANCH}
